import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  header: {
    position: "relative",
    height: 88,
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
  },
  title: {
    paddingHorizontal: 40,
    paddingVertical: 11,
    fontFamily: "Roboto-Medium",
    fontWeight: "500",
    fontSize: 17,
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: 0.01,
    color: "#212121",
  },
  backBtn: {
    position: "absolute",
    left: 20,
    bottom: 10,
  },
  postsBox: {
    width: "100%",
    paddingTop: 32,
    paddingBottom: 440,
  },
  photoSection: {
    width: 343,
    height: 240,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: "#E8E8E8",
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: 32,
    backgroundColor: "#F6F6F6",
  },
  post: {
    width: "100%",
    height: "100%",
    marginBottom: 8,
    borderRadius: 8,
  },
  commentSection: {
    display: "flex",
    flexDirection: "row",
    width: 343,
    marginLeft: "auto",
    marginRight: "auto",
  },
  userAvatarBox: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  userAvatar: {
    width: "100%",
    height: "100%",
  },
  commentBox: {
    width: 299,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 16,
    borderBottomLeftRadius: 6,
    borderBottomRightRadius: 6,
    marginBottom: 24,
    backgroundColor: "rgba(0, 0, 0, 0.03)",
  },
  companionComment: {
    marginLeft: "auto",
    borderTopLeftRadius: 0,
    borderTopRightRadius: 6,
  },
  userComment: {
    marginRight: "auto",
    borderTopLeftRadius: 6,
    borderTopRightRadius: 0,
  },
  comment: {
    marginBottom: 8,
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 13,
    lineHeight: 18,
  },
  commentDate: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 10,
    lineHeight: 11.72,
    color: "#BDBDBD",
  },
  sendBtn: {
    position: "absolute",
    bottom: 24,
    right: 8,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FF6C00",
  },
  commentInput: {
    width: 343,
    height: 50,
    paddingTop: 16,
    paddingBottom: 15,
    paddingLeft: 16,
    borderWidth: 1,
    borderRadius: 25,
    marginBottom: 16,
    borderColor: "#E8E8E8",
    backgroundColor: "#F6F6F6",
    fontFamily: "Inter-Regular",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 19,
  },
});
