import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    position: "relative",
    paddingTop: 120,
    backgroundColor: "#FFFFFF",
  },
  header: {
    position: "absolute",
    top: 0,
    height: 88,
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
  },
  title: {
    paddingHorizontal: 40,
    paddingVertical: 11,
    fontFamily: "Roboto-Medium",
    fontWeight: "500",
    fontSize: 17,
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: 0.01,
    color: "#212121",
  },
  backBtn: {
    position: "absolute",
    left: 16,
    bottom: 10,
  },
  photoSection: {
    position: "relative",
    width: 343,
    height: 240,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: "#E8E8E8",
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: 59,
    backgroundColor: "#F6F6F6",
  },
  photoLoadTitle: {
    position: "absolute",
    bottom: -27,
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "#BDBDBD",
  },
  cameraIconBox: {
    position: "absolute",
    top: 90,
    left: 142,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  locationBox: {
    position: "relative",
    width: 343,
    height: 50,
    marginBottom: 32,
  },
  locationSvg: {
    position: "absolute",
    top: 13,
    left: 0,
  },
  postForm: {
    display: "flex",
    alignItems: "center",
    borderRadius: 16,
    marginBottom: 111,
  },
  input: {
    width: 343,
    height: 50,
    paddingTop: 16,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#E8E8E8",
    fontFamily: "Roboto-Regular",
    fontSize: 16,
  },
  postBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 343,
    height: 51,
    borderRadius: 100,
  },
  postBtnText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    color: "#BDBDBD",
  },
  footer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    height: 83,
  },
  deletePostBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 70,
    height: 40,
    borderRadius: 20,
    marginLeft: 31,
    marginRight: 31,
    backgroundColor: "#F6F6F6",
  },
});
