import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    height: "100%",
    backgroundColor: "#FFFFFF",
  },
  header: {
    position: "relative",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    height: 88,
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
  },
  title: {
    paddingHorizontal: 40,
    paddingVertical: 11,
    fontFamily: "Roboto-Medium",
    fontWeight: "500",
    fontSize: 17,
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: 0.01,
    color: "#212121",
  },
  logOutBtn: {
    position: "absolute",
    right: 16,
    bottom: 10,
  },
  user: {
    position: "absolute",
    top: 120,
    left: 16,
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    borderRadius: 16,
  },
  userPhoto: {
    width: 60,
    height: 60,
    marginRight: 8,
    borderRadius: 16,
    backgroundColor: "#F6F6F6",
  },
  userName: {
    fontFamily: "Roboto-Medium",
    fontWeight: "700",
    fontSize: 13,
    lineHeight: 15,
    color: "#212121",
  },
  userEmail: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 11,
    lineHeight: 13,
    color: "#212121",
  },
  footer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    height: 83,
    borderTopWidth: 1,
    borderTopColor: "#E5E5E5",
    width: "100%",
  },
  addPostBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 70,
    height: 40,
    borderRadius: 100,
    marginLeft: 31,
    marginRight: 31,
    backgroundColor: "#FF6C00",
  },
});
