import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ecf0f1",
  },
  image: {
    flex: 1,
    justifyContent: "center",
    resizeMode: "cover",
    paddingTop: 147,
  },
  userName: {
    marginBottom: 32,
    fontFamily: "Roboto-Medium",
    fontWeight: "500",
    fontSize: 30,
    lineHeight: 35,
    textAlign: "center",
    letterSpacing: 0.01,
    color: "#212121",
  },
  logOutBtn: {
    position: "absolute",
    top: 22,
    right: 16,
  },
  deleteAvatarBtn: {
    position: "absolute",
    zIndex: 1,
    elevation: 1,
    bottom: 14,
    right: -12.5,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 25,
    height: 25,
    borderWidth: 1,
    borderRadius: 12.5,
    borderColor: "#E8E8E8",
    backgroundColor: "#FFFFFF",
  },
  form: {
    display: "flex",
    width: "100%",
    height: "100%",
    alignItems: "center",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingTop: 92,
    backgroundColor: "#FFFFFF",
  },
  photoSection: {
    width: 343,
    height: 240,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: "#E8E8E8",
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: 8,
    backgroundColor: "#F6F6F6",
  },
  post: {
    width: "100%",
    height: "100%",
    borderRadius: 8,
  },
  avatar: {
    position: "absolute",
    top: -60,
    width: 120,
    height: 120,
    borderRadius: 16,
    backgroundColor: "#F6F6F6",
  },
  commentSection: {
    display: "flex",
    flexDirection: "row",
    width: 343,
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: 32,
  },
  description: {
    marginBottom: 8,
    fontFamily: "Roboto-Medium",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 18.75,
  },
  comment: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
  },
  reactions: {
    marginRight: 6,
  },
  map: {
    marginRight: 4,
  },
  postItem: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  footer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    width: "100%",
    height: 83,
    borderTopWidth: 1,
    borderTopColor: "#E5E5E5",
    backgroundColor: "#FFFFFF",
  },
  user: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 70,
    height: 40,
    borderRadius: 100,
    marginLeft: 31,
    marginRight: 31,
    backgroundColor: "#FF6C00",
  },
  addBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
});
