import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  header: {
    position: "relative",
    height: 88,
    width: "100%",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
  },
  title: {
    paddingHorizontal: 40,
    paddingVertical: 11,
    fontFamily: "Roboto-Medium",
    fontWeight: "500",
    fontSize: 17,
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: 0.01,
    color: "#212121",
  },
  logOutBtn: {
    position: "absolute",
    right: 16,
    bottom: 10,
  },
  postsBox: {
    width: "100%",
    marginBottom: 170,
  },
  user: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    borderRadius: 16,
    marginBottom: 32,
    marginLeft: "6%",
  },
  userPhoto: {
    width: 60,
    height: 60,
    marginRight: 8,
    borderRadius: 16,
    backgroundColor: "#F6F6F6",
  },
  userName: {
    fontFamily: "Roboto-Medium",
    fontWeight: "700",
    fontSize: 13,
    lineHeight: 15,
    color: "#212121",
  },
  userEmail: {
    fontFamily: "Roboto",
    fontWeight: "400",
    fontSize: 11,
    lineHeight: 13,
    color: "#212121",
  },
  scroll: {
    paddingTop: 32,
  },
  photoSection: {
    width: 343,
    height: 240,
    borderWidth: 1,
    borderRadius: 8,
    borderColor: "#E8E8E8",
    marginLeft: "auto",
    marginRight: "auto",
    marginBottom: 91,
    backgroundColor: "#F6F6F6",
  },
  post: {
    width: "100%",
    height: "100%",
    marginBottom: 8,
    borderRadius: 8,
  },
  postTitle: {
    marginBottom: 8,
    fontFamily: "Roboto-Medium",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 19,
  },
  captionBox: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
  },
  captionTitle: {
    fontFamily: "Roboto",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
  },
  commentAndLocation: {
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    height: 83,
    borderTopWidth: 1,
    borderTopColor: "#E5E5E5",
    backgroundColor: "#FFFFFF",
    width: "100%",
  },
  addPostBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: 70,
    height: 40,
    borderRadius: 100,
    marginLeft: 31,
    marginRight: 31,
    backgroundColor: "#FF6C00",
  },
});
